021-10-26 14:25:27,223 () volttron.platform.auth WARNING: Attempt 1 to get peerlist failed with exception 0.5 seconds
2021-10-26 14:25:27,224 () volttron.platform.auth WARNING: Get list of peers from subsystem directly
2021-10-26 14:25:27,241 () volttron.platform.auth INFO: auth file /home/developer/.volttron/auth.json loaded
2021-10-26 14:25:27,244 () volttron.platform.auth INFO: loading auth file /home/developer/.volttron/auth.json
2021-10-26 14:25:29,768 () volttron.platform.auth WARNING: Attempt 1 to get peerlist failed with exception 0.5 seconds
2021-10-26 14:25:29,769 () volttron.platform.auth WARNING: Get list of peers from subsystem directly
2021-10-26 14:25:29,786 () volttron.platform.auth INFO: auth file /home/developer/.volttron/auth.json loaded
2021-10-26 14:26:00,000 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:27:00+00:00
2021-10-26 14:26:00,001 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:26:00,005 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:26:00,005 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:26:00,186 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Received read response from 26300:1 count: 3
2021-10-26 14:26:00,190 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: publishing: devices/kirkland/2227623/all
2021-10-26 14:26:00,195 (vcplatformagent-4.8 6180) __main__ DEBUG: topic: devices/kirkland/2227623/all, message: [{'kW_Max_Demand': 188.56858825683594, 'kW_Total': 22.45187759399414, 'kWh': 680922.375}, {'kWh': {'units': 'kilowattHours', 'type': 'float', 'tz': ''}, 'kW_Total': {'units': 'kilowatts', 'type': 'float', 'tz': ''}, 'kW_Max_Demand': {'units': 'kilowatts', 'type': 'float', 'tz': ''}}]
2021-10-26 14:26:00,196 (vcplatformagent-4.8 6180) __main__ DEBUG: _topic_replace_list  is {}
2021-10-26 14:26:00,200 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: finish publishing: devices/kirkland/2227623/all
2021-10-26 14:26:00,218 (forwarderagent-5.1 6178) __main__ DEBUG: publish_to_historian number of items: 1
2021-10-26 14:26:00,218 (forwarderagent-5.1 6178) __main__ DEBUG: Lasttime: 0 currenttime: 1635258360.0
2021-10-26 14:26:00,310 (forwarderagent-5.1 6178) __main__ DEBUG: handled: 1 number of items
2021-10-26 14:27:00,002 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:28:00+00:00
2021-10-26 14:27:00,003 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:27:00,011 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:27:00,011 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:27:00,271 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Received read response from 26300:1 count: 3
2021-10-26 14:27:00,281 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: publishing: devices/kirkland/2227623/all
2021-10-26 14:27:00,291 (vcplatformagent-4.8 6180) __main__ DEBUG: topic: devices/kirkland/2227623/all, message: [{'kW_Max_Demand': 188.56858825683594, 'kW_Total': 21.950403213500977, 'kWh': 680922.8125}, {'kWh': {'units': 'kilowattHours', 'type': 'float', 'tz': ''}, 'kW_Total': {'units': 'kilowatts', 'type': 'float', 'tz': ''}, 'kW_Max_Demand': {'units': 'kilowatts', 'type': 'float', 'tz': ''}}]
2021-10-26 14:27:00,292 (vcplatformagent-4.8 6180) __main__ DEBUG: _topic_replace_list  is {}
2021-10-26 14:27:00,298 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: finish publishing: devices/kirkland/2227623/all
2021-10-26 14:27:00,315 (forwarderagent-5.1 6178) __main__ DEBUG: publish_to_historian number of items: 1
2021-10-26 14:27:00,315 (forwarderagent-5.1 6178) __main__ DEBUG: Lasttime: 0 currenttime: 1635258420.0
2021-10-26 14:27:00,405 (forwarderagent-5.1 6178) __main__ DEBUG: handled: 1 number of items
2021-10-26 14:28:00,006 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:29:00+00:00
2021-10-26 14:28:00,006 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:28:00,014 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:28:00,015 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:28:00,165 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Received read response from 26300:1 count: 3
2021-10-26 14:28:00,171 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: publishing: devices/kirkland/2227623/all
2021-10-26 14:28:00,179 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: finish publishing: devices/kirkland/2227623/all
2021-10-26 14:28:00,179 (vcplatformagent-4.8 6180) __main__ DEBUG: topic: devices/kirkland/2227623/all, message: [{'kW_Max_Demand': 188.56858825683594, 'kW_Total': 22.308250427246094, 'kWh': 680923.125}, {'kWh': {'units': 'kilowattHours', 'type': 'float', 'tz': ''}, 'kW_Total': {'units': 'kilowatts', 'type': 'float', 'tz': ''}, 'kW_Max_Demand': {'units': 'kilowatts', 'type': 'float', 'tz': ''}}]
2021-10-26 14:28:00,180 (vcplatformagent-4.8 6180) __main__ DEBUG: _topic_replace_list  is {}
2021-10-26 14:28:00,209 (forwarderagent-5.1 6178) __main__ DEBUG: publish_to_historian number of items: 1
2021-10-26 14:28:00,210 (forwarderagent-5.1 6178) __main__ DEBUG: Lasttime: 0 currenttime: 1635258480.0
2021-10-26 14:28:00,299 (forwarderagent-5.1 6178) __main__ DEBUG: handled: 1 number of items
2021-10-26 14:29:00,000 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:30:00+00:00
2021-10-26 14:29:00,001 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:29:00,010 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:29:00,010 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:29:00,168 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Received read response from 26300:1 count: 3
2021-10-26 14:29:00,177 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: publishing: devices/kirkland/2227623/all
2021-10-26 14:29:00,189 (vcplatformagent-4.8 6180) __main__ DEBUG: topic: devices/kirkland/2227623/all, message: [{'kW_Max_Demand': 188.56858825683594, 'kW_Total': 22.678173065185547, 'kWh': 680923.5}, {'kWh': {'units': 'kilowattHours', 'type': 'float', 'tz': ''}, 'kW_Total': {'units': 'kilowatts', 'type': 'float', 'tz': ''}, 'kW_Max_Demand': {'units': 'kilowatts', 'type': 'float', 'tz': ''}}]
2021-10-26 14:29:00,191 (vcplatformagent-4.8 6180) __main__ DEBUG: _topic_replace_list  is {}
2021-10-26 14:29:00,199 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: finish publishing: devices/kirkland/2227623/all
2021-10-26 14:29:00,223 (forwarderagent-5.1 6178) __main__ DEBUG: publish_to_historian number of items: 1
2021-10-26 14:29:00,224 (forwarderagent-5.1 6178) __main__ DEBUG: Lasttime: 0 currenttime: 1635258540.0
2021-10-26 14:29:00,316 (forwarderagent-5.1 6178) __main__ DEBUG: handled: 1 number of items
2021-10-26 14:30:00,002 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:31:00+00:00
2021-10-26 14:30:00,003 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:30:00,011 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:30:00,012 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:30:00,184 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Received read response from 26300:1 count: 3
2021-10-26 14:30:00,190 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: publishing: devices/kirkland/2227623/all
2021-10-26 14:30:00,197 (vcplatformagent-4.8 6180) __main__ DEBUG: topic: devices/kirkland/2227623/all, message: [{'kW_Max_Demand': 188.56858825683594, 'kW_Total': 22.867473602294922, 'kWh': 680923.875}, {'kWh': {'units': 'kilowattHours', 'type': 'float', 'tz': ''}, 'kW_Total': {'units': 'kilowatts', 'type': 'float', 'tz': ''}, 'kW_Max_Demand': {'units': 'kilowatts', 'type': 'float', 'tz': ''}}]
2021-10-26 14:30:00,198 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: finish publishing: devices/kirkland/2227623/all
2021-10-26 14:30:00,200 (vcplatformagent-4.8 6180) __main__ DEBUG: _topic_replace_list  is {}
2021-10-26 14:30:00,216 (forwarderagent-5.1 6178) __main__ DEBUG: publish_to_historian number of items: 1
2021-10-26 14:30:00,217 (forwarderagent-5.1 6178) __main__ DEBUG: Lasttime: 0 currenttime: 1635258600.0
2021-10-26 14:30:00,307 (forwarderagent-5.1 6178) __main__ DEBUG: handled: 1 number of items
2021-10-26 14:31:00,004 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:32:00+00:00
2021-10-26 14:31:00,005 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:31:00,013 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:31:00,014 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:31:00,169 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Received read response from 26300:1 count: 3
2021-10-26 14:31:00,175 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: publishing: devices/kirkland/2227623/all
2021-10-26 14:31:00,183 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: finish publishing: devices/kirkland/2227623/all
2021-10-26 14:31:00,183 (vcplatformagent-4.8 6180) __main__ DEBUG: topic: devices/kirkland/2227623/all, message: [{'kW_Max_Demand': 188.56858825683594, 'kW_Total': 23.217300415039062, 'kWh': 680924.25}, {'kWh': {'units': 'kilowattHours', 'type': 'float', 'tz': ''}, 'kW_Total': {'units': 'kilowatts', 'type': 'float', 'tz': ''}, 'kW_Max_Demand': {'units': 'kilowatts', 'type': 'float', 'tz': ''}}]
2021-10-26 14:31:00,186 (vcplatformagent-4.8 6180) __main__ DEBUG: _topic_replace_list  is {}
2021-10-26 14:31:00,200 (forwarderagent-5.1 6178) __main__ DEBUG: publish_to_historian number of items: 1
2021-10-26 14:31:00,201 (forwarderagent-5.1 6178) __main__ DEBUG: Lasttime: 0 currenttime: 1635258660.0
2021-10-26 14:31:00,289 (forwarderagent-5.1 6178) __main__ DEBUG: handled: 1 number of items
2021-10-26 14:32:00,005 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:33:00+00:00
2021-10-26 14:32:00,005 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:32:00,010 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:32:00,010 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:32:00,174 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Received read response from 26300:1 count: 3
2021-10-26 14:32:00,178 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: publishing: devices/kirkland/2227623/all
2021-10-26 14:32:00,183 (vcplatformagent-4.8 6180) __main__ DEBUG: topic: devices/kirkland/2227623/all, message: [{'kW_Max_Demand': 188.56858825683594, 'kW_Total': 23.564058303833008, 'kWh': 680924.625}, {'kWh': {'units': 'kilowattHours', 'type': 'float', 'tz': ''}, 'kW_Total': {'units': 'kilowatts', 'type': 'float', 'tz': ''}, 'kW_Max_Demand': {'units': 'kilowatts', 'type': 'float', 'tz': ''}}]
2021-10-26 14:32:00,183 (vcplatformagent-4.8 6180) __main__ DEBUG: _topic_replace_list  is {}
2021-10-26 14:32:00,183 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: finish publishing: devices/kirkland/2227623/all
2021-10-26 14:32:00,199 (forwarderagent-5.1 6178) __main__ DEBUG: publish_to_historian number of items: 1
2021-10-26 14:32:00,199 (forwarderagent-5.1 6178) __main__ DEBUG: Lasttime: 0 currenttime: 1635258720.0
2021-10-26 14:32:00,286 (forwarderagent-5.1 6178) __main__ DEBUG: handled: 1 number of items
2021-10-26 14:33:00,006 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:34:00+00:00
2021-10-26 14:33:00,006 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:33:00,016 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:33:00,017 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:33:00,183 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Received read response from 26300:1 count: 3
2021-10-26 14:33:00,191 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: publishing: devices/kirkland/2227623/all
2021-10-26 14:33:00,203 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: finish publishing: devices/kirkland/2227623/all
2021-10-26 14:33:00,200 (vcplatformagent-4.8 6180) __main__ DEBUG: topic: devices/kirkland/2227623/all, message: [{'kW_Max_Demand': 188.56858825683594, 'kW_Total': 25.255144119262695, 'kWh': 680925.0}, {'kWh': {'units': 'kilowattHours', 'type': 'float', 'tz': ''}, 'kW_Total': {'units': 'kilowatts', 'type': 'float', 'tz': ''}, 'kW_Max_Demand': {'units': 'kilowatts', 'type': 'float', 'tz': ''}}]
2021-10-26 14:33:00,206 (vcplatformagent-4.8 6180) __main__ DEBUG: _topic_replace_list  is {}
2021-10-26 14:33:00,221 (forwarderagent-5.1 6178) __main__ DEBUG: publish_to_historian number of items: 1
2021-10-26 14:33:00,222 (forwarderagent-5.1 6178) __main__ DEBUG: Lasttime: 0 currenttime: 1635258780.0
2021-10-26 14:33:00,310 (forwarderagent-5.1 6178) __main__ DEBUG: handled: 1 number of items
2021-10-26 14:34:00,005 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:35:00+00:00
2021-10-26 14:34:00,006 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:34:00,013 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:34:00,014 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:34:00,179 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Received read response from 26300:1 count: 3
2021-10-26 14:34:00,183 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: publishing: devices/kirkland/2227623/all
2021-10-26 14:34:00,190 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: finish publishing: devices/kirkland/2227623/all
2021-10-26 14:34:00,190 (vcplatformagent-4.8 6180) __main__ DEBUG: topic: devices/kirkland/2227623/all, message: [{'kW_Max_Demand': 188.56858825683594, 'kW_Total': 27.78126335144043, 'kWh': 680925.5}, {'kWh': {'units': 'kilowattHours', 'type': 'float', 'tz': ''}, 'kW_Total': {'units': 'kilowatts', 'type': 'float', 'tz': ''}, 'kW_Max_Demand': {'units': 'kilowatts', 'type': 'float', 'tz': ''}}]
2021-10-26 14:34:00,190 (vcplatformagent-4.8 6180) __main__ DEBUG: _topic_replace_list  is {}
2021-10-26 14:34:00,205 (forwarderagent-5.1 6178) __main__ DEBUG: publish_to_historian number of items: 1
2021-10-26 14:34:00,206 (forwarderagent-5.1 6178) __main__ DEBUG: Lasttime: 0 currenttime: 1635258840.0
2021-10-26 14:34:00,298 (forwarderagent-5.1 6178) __main__ DEBUG: handled: 1 number of items
2021-10-26 14:35:00,002 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:36:00+00:00
2021-10-26 14:35:00,003 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:35:00,011 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:35:00,012 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:35:09,113 (bacnet_proxyagent-0.5 18248) volttron.platform.vip.agent.subsystems.rpc ERROR: unhandled exception in JSON-RPC method 'read_properties': 
Traceback (most recent call last):
  File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
    return method(*args, **kwargs)
  File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
    bacnet_results = iocb.ioResult.get(10)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
RuntimeError: BRS BRS Device communication aborted: noResponse

2021-10-26 14:35:09,114 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: ERROR:volttron.platform.vip.agent.subsystems.rpc:unhandled exception in JSON-RPC method 'read_properties': 
2021-10-26 14:35:09,115 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: Traceback (most recent call last):
2021-10-26 14:35:09,116 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
2021-10-26 14:35:09,116 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     return method(*args, **kwargs)
2021-10-26 14:35:09,119 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
2021-10-26 14:35:09,120 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     bacnet_results = iocb.ioResult.get(10)
2021-10-26 14:35:09,121 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:35:09,122 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:35:09,123 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:35:09,123 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
2021-10-26 14:35:09,124 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
2021-10-26 14:35:09,125 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     raise value
2021-10-26 14:35:09,126 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: RuntimeError: BRS BRS Device communication aborted: noResponse
2021-10-26 14:35:09,128 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: 
2021-10-26 14:35:09,124 (platform_driveragent-4.0 6179) platform_driver.driver ERROR: Failed to scrape kirkland/2227623:
Traceback (most recent call last):
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/driver.py", line 244, in periodic_read
    results = self.interface.scrape_all()
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/interfaces/bacnet.py", line 169, in scrape_all
    self.max_per_request, self.use_read_multiple).get(timeout=self.timeout)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
volttron.platform.jsonrpc.RemoteError: builtins.RuntimeError('BRS BRS Device communication aborted: noResponse')

2021-10-26 14:36:00,002 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:37:00+00:00
2021-10-26 14:36:00,002 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:36:00,006 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:36:00,007 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:36:09,103 (bacnet_proxyagent-0.5 18248) volttron.platform.vip.agent.subsystems.rpc ERROR: unhandled exception in JSON-RPC method 'read_properties': 
Traceback (most recent call last):
  File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
    return method(*args, **kwargs)
  File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
    bacnet_results = iocb.ioResult.get(10)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
RuntimeError: BRS BRS Device communication aborted: noResponse

2021-10-26 14:36:09,105 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: ERROR:volttron.platform.vip.agent.subsystems.rpc:unhandled exception in JSON-RPC method 'read_properties': 
2021-10-26 14:36:09,106 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: Traceback (most recent call last):
2021-10-26 14:36:09,106 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
2021-10-26 14:36:09,107 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     return method(*args, **kwargs)
2021-10-26 14:36:09,107 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
2021-10-26 14:36:09,108 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     bacnet_results = iocb.ioResult.get(10)
2021-10-26 14:36:09,109 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:36:09,110 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:36:09,110 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:36:09,111 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
2021-10-26 14:36:09,112 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
2021-10-26 14:36:09,113 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     raise value
2021-10-26 14:36:09,116 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: RuntimeError: BRS BRS Device communication aborted: noResponse
2021-10-26 14:36:09,120 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: 
2021-10-26 14:36:09,123 (platform_driveragent-4.0 6179) platform_driver.driver ERROR: Failed to scrape kirkland/2227623:
Traceback (most recent call last):
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/driver.py", line 244, in periodic_read
    results = self.interface.scrape_all()
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/interfaces/bacnet.py", line 169, in scrape_all
    self.max_per_request, self.use_read_multiple).get(timeout=self.timeout)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
volttron.platform.jsonrpc.RemoteError: builtins.RuntimeError('BRS BRS Device communication aborted: noResponse')

2021-10-26 14:37:00,005 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:38:00+00:00
2021-10-26 14:37:00,005 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:37:00,014 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:37:00,014 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:37:09,104 (bacnet_proxyagent-0.5 18248) volttron.platform.vip.agent.subsystems.rpc ERROR: unhandled exception in JSON-RPC method 'read_properties': 
Traceback (most recent call last):
  File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
    return method(*args, **kwargs)
  File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
    bacnet_results = iocb.ioResult.get(10)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
RuntimeError: BRS BRS Device communication aborted: noResponse

2021-10-26 14:37:09,105 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: ERROR:volttron.platform.vip.agent.subsystems.rpc:unhandled exception in JSON-RPC method 'read_properties': 
2021-10-26 14:37:09,106 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: Traceback (most recent call last):
2021-10-26 14:37:09,107 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
2021-10-26 14:37:09,110 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     return method(*args, **kwargs)
2021-10-26 14:37:09,111 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
2021-10-26 14:37:09,116 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     bacnet_results = iocb.ioResult.get(10)
2021-10-26 14:37:09,117 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:37:09,118 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:37:09,118 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:37:09,119 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
2021-10-26 14:37:09,120 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
2021-10-26 14:37:09,121 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     raise value
2021-10-26 14:37:09,121 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: RuntimeError: BRS BRS Device communication aborted: noResponse
2021-10-26 14:37:09,122 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: 
2021-10-26 14:37:09,115 (platform_driveragent-4.0 6179) platform_driver.driver ERROR: Failed to scrape kirkland/2227623:
Traceback (most recent call last):
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/driver.py", line 244, in periodic_read
    results = self.interface.scrape_all()
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/interfaces/bacnet.py", line 169, in scrape_all
    self.max_per_request, self.use_read_multiple).get(timeout=self.timeout)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
volttron.platform.jsonrpc.RemoteError: builtins.RuntimeError('BRS BRS Device communication aborted: noResponse')

2021-10-26 14:38:00,005 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:39:00+00:00
2021-10-26 14:38:00,006 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:38:00,014 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:38:00,015 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:38:09,103 (bacnet_proxyagent-0.5 18248) volttron.platform.vip.agent.subsystems.rpc ERROR: unhandled exception in JSON-RPC method 'read_properties': 
Traceback (most recent call last):
  File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
    return method(*args, **kwargs)
  File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
    bacnet_results = iocb.ioResult.get(10)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
RuntimeError: BRS BRS Device communication aborted: noResponse

2021-10-26 14:38:09,105 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: ERROR:volttron.platform.vip.agent.subsystems.rpc:unhandled exception in JSON-RPC method 'read_properties': 
2021-10-26 14:38:09,106 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: Traceback (most recent call last):
2021-10-26 14:38:09,106 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
2021-10-26 14:38:09,106 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     return method(*args, **kwargs)
2021-10-26 14:38:09,107 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
2021-10-26 14:38:09,107 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     bacnet_results = iocb.ioResult.get(10)
2021-10-26 14:38:09,107 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:38:09,108 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:38:09,108 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:38:09,108 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
2021-10-26 14:38:09,109 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
2021-10-26 14:38:09,109 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     raise value
2021-10-26 14:38:09,110 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: RuntimeError: BRS BRS Device communication aborted: noResponse
2021-10-26 14:38:09,110 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: 
2021-10-26 14:38:09,107 (platform_driveragent-4.0 6179) platform_driver.driver ERROR: Failed to scrape kirkland/2227623:
Traceback (most recent call last):
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/driver.py", line 244, in periodic_read
    results = self.interface.scrape_all()
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/interfaces/bacnet.py", line 169, in scrape_all
    self.max_per_request, self.use_read_multiple).get(timeout=self.timeout)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
volttron.platform.jsonrpc.RemoteError: builtins.RuntimeError('BRS BRS Device communication aborted: noResponse')

2021-10-26 14:39:00,005 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: kirkland/2227623 next scrape scheduled: 2021-10-26 14:40:00+00:00
2021-10-26 14:39:00,006 (platform_driveragent-4.0 6179) platform_driver.driver DEBUG: scraping device: kirkland/2227623
2021-10-26 14:39:00,015 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Reading 3 points on 26300:1, max per scrape: 24
2021-10-26 14:39:00,016 (bacnet_proxyagent-0.5 18248) __main__ DEBUG: Requesting 3 properties from 26300:1
2021-10-26 14:39:00,321 (forwarderagent-5.1 6178) volttron.platform.agent.base_historian DEBUG: Queue wait timed out. Falling out.
2021-10-26 14:39:09,103 (bacnet_proxyagent-0.5 18248) volttron.platform.vip.agent.subsystems.rpc ERROR: unhandled exception in JSON-RPC method 'read_properties': 
Traceback (most recent call last):
  File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
    return method(*args, **kwargs)
  File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
    bacnet_results = iocb.ioResult.get(10)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
RuntimeError: BRS BRS Device communication aborted: noResponse

2021-10-26 14:39:09,105 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: ERROR:volttron.platform.vip.agent.subsystems.rpc:unhandled exception in JSON-RPC method 'read_properties': 
2021-10-26 14:39:09,106 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: Traceback (most recent call last):
2021-10-26 14:39:09,106 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
2021-10-26 14:39:09,111 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     return method(*args, **kwargs)
2021-10-26 14:39:09,112 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/.volttron/agents/39f3c2f7-9ac6-440f-915b-f9a9a00cb8b2/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 770, in read_properties
2021-10-26 14:39:09,113 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     bacnet_results = iocb.ioResult.get(10)
2021-10-26 14:39:09,114 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:39:09,115 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:39:09,116 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
2021-10-26 14:39:09,117 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
2021-10-26 14:39:09,118 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:   File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
2021-10-26 14:39:09,119 (bacnet_proxyagent-0.5 18248) <stderr> ERROR:     raise value
2021-10-26 14:39:09,119 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: RuntimeError: BRS BRS Device communication aborted: noResponse
2021-10-26 14:39:09,120 (bacnet_proxyagent-0.5 18248) <stderr> ERROR: 
2021-10-26 14:39:09,115 (platform_driveragent-4.0 6179) platform_driver.driver ERROR: Failed to scrape kirkland/2227623:
Traceback (most recent call last):
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/driver.py", line 244, in periodic_read
    results = self.interface.scrape_all()
  File "/home/developer/.volttron/agents/8c9ff357-6f1a-42d7-9f9f-28ef49e88cb8/platform_driveragent-4.0/platform_driver/interfaces/bacnet.py", line 169, in scrape_all
    self.max_per_request, self.use_read_multiple).get(timeout=self.timeout)
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
    raise value
volttron.platform.jsonrpc.RemoteError: builtins.RuntimeError('BRS BRS Device communication aborted: noResponse')
    
    
    
    RuntimeError: Device communication aborted: noResponse

2022-03-28 18:27:09,106 (bacnet_proxyagent-0.5 23580) <stderr> ERROR: ERROR:volttron.platform.vip.agent.subsystems.rpc:unhandled exception in JSON-RPC method 'read_properties': 
2022-03-28 18:27:09,106 (bacnet_proxyagent-0.5 23580) <stderr> ERROR: Traceback (most recent call last):
2022-03-28 18:27:09,107 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:   File "/home/developer/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 181, in method
2022-03-28 18:27:09,107 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:     return method(*args, **kwargs)
2022-03-28 18:27:09,109 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:   File "/home/developer/.volttron/agents/8871b34a-25c5-483f-a602-452b0bbf84be/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 774, in read_properties
2022-03-28 18:27:09,110 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:     bacnet_results = iocb.ioResult.get(10)
2022-03-28 18:27:09,110 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:   File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
2022-03-28 18:27:09,111 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:   File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
2022-03-28 18:27:09,111 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:   File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
2022-03-28 18:27:09,112 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:   File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
2022-03-28 18:27:09,112 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:   File "/home/developer/volttron/env/lib/python3.7/site-packages/gevent/_compat.py", line 66, in reraise
2022-03-28 18:27:09,112 (bacnet_proxyagent-0.5 23580) <stderr> ERROR:     raise value
2022-03-28 18:27:09,113 (bacnet_proxyagent-0.5 23580) <stderr> ERROR: RuntimeError: Device communication aborted: noResponse
2022-03-28 18:27:09,114 (bacnet_proxyagent-0.5 23580) <stderr> ERROR: 
2022-03-28 18:27:09,461 () volttron.platform.auth INFO: loading auth file /home/developer/.volttron/auth.json
20

    
    
    =['SXr9p0DYyP3K_ixoDz5WeGGfIHYN00WVj4K9Ouq2n0k'], user='control.connection'
2022-03-28 18:35:29,797 () volttron.platform.auth INFO: AUTH: After authenticate user id: 'control.connection', b'9b278d09-fa15-4520-b182-c72961a521aa'
2022-03-28 18:35:29,797 () volttron.platform.auth INFO: authentication success: userid=b'9b278d09-fa15-4520-b182-c72961a521aa' domain='vip', address='localhost:1001:1001:25538', mechanism='CURVE', credentials=['SXr9p0DYyP3K_ixoDz5WeGGfIHYN00WVj4K9Ouq2n0k'], user='control.connection'
2022-03-28 18:35:44,379 () volttron.platform.auth INFO: AUTH: After authenticate user id: 'control.connection', b'9b278d09-fa15-4520-b182-c72961a521aa'
2022-03-28 18:35:44,379 () volttron.platform.auth INFO: authentication success: userid=b'9b278d09-fa15-4520-b182-c72961a521aa' domain='vip', address='localhost:1001:1001:25610', mechanism='CURVE', credentials=['SXr9p0DYyP3K_ixoDz5WeGGfIHYN00WVj4K9Ouq2n0k'], user='control.connection'
2022-03-28 18:35:44,773 (forwarderagent-5.1 23581) volttron.platform.agent.base_historian DEBUG: Stopping the process loop.
2022-03-28 18:35:44,777 (forwarderagent-5.1 23581) volttron.platform.agent.base_historian DEBUG: Process loop stopped.
2022-03-28 18:35:44,778 (forwarderagent-5.1 23581) volttron.platform.agent.base_historian DEBUG: Process loop stopped.
2022-03-28 18:35:44,778 (forwarderagent-5.1 23581) volttron.platform.vip.agent.subsystems.pubsub DEBUG: AFTER: defaultdict(<function PubSub.__init__.<locals>.platform_subscriptions at 0xb4bf94b0>, {'internal': defaultdict(<function PubSub.__init__.<locals>.subscriptions at 0xb4bf94f8>, {'': defaultdict(<class 'set'>, {'devices': {<bound method ForwardHistorian._capture_device_data of <__main__.ForwardHistorian object at 0xb4bd7110>>}, Topic('datalogger'): {<bound method ForwardHistorian._capture_log_data of <__main__.ForwardHistorian object at 0xb4bd7110>>}, 'analysis': {<bound method ForwardHistorian._capture_analysis_data of <__main__.ForwardHistorian object at 0xb4bd7110>>}, Topic('record'): {<bound method ForwardHistorian._capture_record_data of <__main__.ForwardHistorian object at 0xb4bd7110>>}})})})
2022-03-28 18:35:44,779 (forwarderagent-5.1 23581) volttron.platform.vip.agent.subsystems.pubsub DEBUG: AFTER: defaultdict(<function PubSub.__init__.<locals>.platform_subscriptions at 0xb4bf94b0>, {'internal': defaultdict(<function PubSub.__init__.<locals>.subscriptions at 0xb4bf94f8>, {'': defaultdict(<class 'set'>, {'devices': {<bound method ForwardHistorian._capture_device_data of <__main__.ForwardHistorian object at 0xb4bd7110>>}, Topic('datalogger'): {<bound method ForwardHistorian._capture_log_data of <__main__.ForwardHistorian object at 0xb4bd7110>>}, 'analysis': {<bound method ForwardHistorian._capture_analysis_data of <__main__.ForwardHistorian object at 0xb4bd7110>>}, Topic('record'): {<bound method ForwardHistorian._capture_record_data of <__main__.ForwardHistorian object at 0xb4bd7110>>}})})})
2022-03-28 18:35:45,116 (platform_driveragent-4.0 24885) <stderr> ERROR: Traceback (most recent call last):
2022-03-28 18:35:45,117 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
2022-03-28 18:35:45,117 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "/home/developer/.volttron/agents/7443a893-d89d-4605-8721-7482e1571c94/platform_driveragent-4.0/platform_driver/driver.py", line 163, in starting
2022-03-28 18:35:45,118 (platform_driveragent-4.0 24885) <stderr> ERROR:     self.setup_device()
2022-03-28 18:35:45,119 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "/home/developer/.volttron/agents/7443a893-d89d-4605-8721-7482e1571c94/platform_driveragent-4.0/platform_driver/driver.py", line 186, in setup_device
2022-03-28 18:35:45,119 (platform_driveragent-4.0 24885) <stderr> ERROR:     self.interface = self.get_interface(driver_type, driver_config, registry_config)
2022-03-28 18:35:45,120 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "/home/developer/.volttron/agents/7443a893-d89d-4605-8721-7482e1571c94/platform_driveragent-4.0/platform_driver/driver.py", line 158, in get_interface
2022-03-28 18:35:45,121 (platform_driveragent-4.0 24885) <stderr> ERROR:     interface.configure(config_dict, config_string)
2022-03-28 18:35:45,122 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "/home/developer/.volttron/agents/7443a893-d89d-4605-8721-7482e1571c94/platform_driveragent-4.0/platform_driver/interfaces/bacnet.py", line 92, in configure
2022-03-28 18:35:45,122 (platform_driveragent-4.0 24885) <stderr> ERROR:     self.ping_target()
2022-03-28 18:35:45,123 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "/home/developer/.volttron/agents/7443a893-d89d-4605-8721-7482e1571c94/platform_driveragent-4.0/platform_driver/interfaces/bacnet.py", line 111, in ping_target
2022-03-28 18:35:45,124 (platform_driveragent-4.0 24885) <stderr> ERROR:     self.vip.rpc.call(self.proxy_address, 'ping_device', self.target_address, self.device_id).get(timeout=self.timeout)
2022-03-28 18:35:45,125 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
2022-03-28 18:35:45,126 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/event.py", line 332, in gevent._gevent_cevent.AsyncResult.get
2022-03-28 18:35:45,126 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/_abstract_linkable.py", line 346, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
2022-03-28 18:35:45,127 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/_abstract_linkable.py", line 348, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
2022-03-28 18:35:45,128 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/_abstract_linkable.py", line 303, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
2022-03-28 18:35:45,129 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
2022-03-28 18:35:45,130 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
2022-03-28 18:35:45,130 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
2022-03-28 18:35:45,131 (platform_driveragent-4.0 24885) <stderr> ERROR:   File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
2022-03-28 18:35:45,132 (platform_driveragent-4.0 24885) <stderr> ERROR: gevent.timeout.Timeout: 30.0 seconds
2022-03-28 18:35:45,133 (platform_driveragent-4.0 24885) <stderr> ERROR: 2022-03-28T18:30:34Z <Greenlet at 0xb4dc6390: <bound method DriverAgent.starting of <platform_driver.driver.DriverAgent object at 0xb4d7bf30>>(<volttron.platform.vip.agent.core.BasicCore object)> failed with Timeout
2022-03-28 18:35:45,134 (platform_driveragent-4.0 24885) <stderr> ERROR: 
2022-03-28 18:35:45,456 (vcplatformagent-4.8 23583) __main__ DEBUG: Shutting down agent.
2022-03-28 18:35:49,974 (platform_driveragent-4.0 25651) root DEBUG: Creating ZMQ Core platform.driver
2022-03-28 18:35:50,061 (forwarderagent-5.1 25650) volttron.platform.agent.base_historian DEBUG: Constructor of BaseHistorian thread: MainThread
2022-03-28 18:35:50,061 (forwarderagent-5.1 25650) volttron.platform.agent.base_historian DEBUG: Constructor of BaseQueryHistorianAgent thread: MainThread
2022-03-28 18:35:50,061 (forwarderagent-5.1 25650) volttron.platform.agent.utils DEBUG: value from env False
2022-03-28 18:35:50,075 (forwarderagent-5.1 25650) <stderr> ERROR: Generating LALR tables
2022-03-28 18:35:50,074 (forwarderagent-5.1 25650) root DEBUG: Creating ZMQ Core fh_kirkland2
2022-03-28 18:35:50,084 (forwarderagent-5.1 25650) volttron.platform.agent.base_historian INFO: Topic string replace list: []
2022-03-28 18:35:50,128 () volttron.platform.auth INFO: AUTH: After authenticate user id: 'platform.driver', b'9b278d09-fa15-4520-b182-c72961a521aa'
2022-03-28 18:35:50,129 () volttron.platform.auth INFO: authentication success: userid=b'9b278d09-fa15-4520-b182-c72961a521aa' domain='vip', address='localhost:1001:1001:25651', mechanism='CURVE', credentials=['iiaptEsXt37Pfot7AncKaZ5Xu98ETMJKbLwt1tLedD0'], user='platform.driver'
2022-03-28 18:35:50,129 (bacnet_proxyagent-0.5 25649) root DEBUG: Creating ZMQ Core platform.bacnet_proxy
2022-03-28 18:35:50,138 (bacnet_proxyagent-0.5 25649) __main__ INFO: seg_supported segmentedBoth
2022-03-28 18:35:50,139 (bacnet_proxyagent-0.5 25649) __main__ INFO: max_apdu_len 1024
2022-03-28 18:35:50,141 (bacnet_proxyagent-0.5 25649) __main__ INFO: obj_id 599
2022-03-28 18:35:50,142 (bacnet_proxyagent-0.5 25649) __main__ INFO: obj_name Volttron BACnet driver
2022-03-28 18:35:50,143 (bacnet_proxyagent-0.5 25649) __main__ INFO: ven_id 5
2022-03-28 18:35:50,166 (platform_driveragent-4.0 25651) volttron.platform.vip.agent.core INFO: Connected to platform: router: 9b278d09-fa15-4520-b182-c72961a521aa version: 1.0 identity: platform.driver
2022-03-28 18:35:50,222 () volttron.platform.auth INFO: AUTH: After authenticate user id: 'fh_kirkland2', b'9b278d09-fa15-4520-b182-c72961a521aa'
2022-03-28 18:35:50,223 () volttron.platform.auth INFO: authentication success: userid=b'9b278d09-fa15-4520-b182-c72961a521aa' domain='vip', address='localhost:1001:1001:25650', mechanism='CURVE', credentials=['LVf8iDHK8OWke3AgCvdrj0-jMK-l31OkDqDlr0r7830'], user='fh_kirkland2'
2022-03-28 18:35:50,226 (platform_driveragent-4.0 25651) volttron.platform.vip.agent.subsystems.configstore DEBUG: Processing callbacks for affected files: {'devices/kirkland/2227623': 'NEW', 'registry_configs/2227623.csv': 'NEW', 'config': 'NEW'}
2022-03-28 18:35:50,228 (platform_driveragent-4.0 25651) __main__ INFO: maximum concurrently open sockets limited to 838860 (derived from system limits)
2022-03-28 18:35:50,228 (platform_driveragent-4.0 25651) __main__ INFO: maximum concurrent driver publishes limited to 10000
2022-03-28 18:35:50,231 (platform_driveragent-4.0 25651) __main__ INFO: In update_driver
2022-03-28 18:35:50,233 (platform_driveragent-4.0 25651) __main__ INFO: Starting driver: kirkland/2227623
2022-03-28 18:35:50,235 (platform_driveragent-4.0 25651) platform_driver.driver DEBUG: kirkland/2227623 group: 0, time_slot: 0, offset: 0.0
2022-03-28 18:35:50,261 () volttron.platform.auth INFO: AUTH: After authenticate user id: 'platform.bacnet_proxy', b'9b278d09-fa15-4520-b182-c72961a521aa'
2022-03-28 18:35:50,266 () volttron.platform.auth INFO: authentication success: userid=b'9b278d09-fa15-4520-b182-c72961a521aa' domain='vip', address='localhost:1001:1001:25649', mechanism='CURVE', credentials=['sjWYeyO4Dc2zEj_kR0_0kIM7tWBPBItHh6RZoRgTBmo'], user='platform.bacnet_proxy'
2022-03-28 18:35:50,264 (forwarderagent-5.1 25650) volttron.platform.vip.agent.core INFO: Connected to platform: router: 9b278d09-fa15-4520-b182-c72961a521aa version: 1.0 identity: fh_kirkland2
2022-03-28 18:35:50,290 (bacnet_proxyagent-0.5 25649) volttron.platform.vip.agent.core INFO: Connected to platform: router: 9b278d09-fa15-4520-b182-c72961a521aa version: 1.0 identity: platform.bacnet_proxy
2022-03-28 18:35:50,295 (forwarderagent-5.1 25650) volttron.platform.vip.agent.subsystems.configstore DEBUG: Processing callbacks for affected files: {'config': 'NEW'}
2022-03-28 18:35:50,309 (forwarderagent-5.1 25650) volttron.platform.agent.base_historian INFO: Topic string replace list: []
2022-03-28 18:35:50,309 (
